version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  build-tags:
    - ""

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
    - unparam
    - gocritic
    - prealloc
    - bodyclose
    - errorlint
    - exhaustive
  disable:
    - gosec  # Too many false positives for a build/package management tool

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - errorsas
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
    disable:
      - shadow

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

  gosec:
    excludes-use-default: false
    exclude-generated: true
    excludes:
      - G204 # Subprocess launched with variable - expected for build tools
      - G304 # File path provided as taint input - expected for package management
      - G306 # Expect WriteFile permissions to be 0600 or less - scripts need exec permission

  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - captLocal
      - dupImport
      - elseif
      - emptyStringTest
      - hexLiteral
      - indexAlloc
      - methodExprCall
      - nilValReturn
      - rangeExprCopy
      - rangeValCopy
      - sloppyReassign
      - stringXbytes
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlambda
      - unnecessaryBlock

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "undefined: yaml"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - revive
      text: "exported: exported function"
    - text: "undefined: yaml"
      linters:
        - typecheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
