version: "2"

run:
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
    - unparam
    - gocritic
    - prealloc
    - bodyclose
    - errorlint
    - exhaustive
  disable:
    - gosec
